### ISSUE TITLE
Feature Request: Add support for ruby blocks

### ISSUE THREAD

**Issue by EthanZeigler** [j0meinaster/bracket-peek#13] opened 2021-02-23 14:58 UTC
Could support be added for the ruby block syntax? I work with a legacy codebase where blocks can be several hundred lines long. This extension's functionality would be extremely helpful for me.

**Comment by j0meinaster** [comment] 2021-02-25 19:17
Would be possible, but would take a lot of effort, since no open-closing matching is possible. There is no closing element at all.

Do you want to see the opening block line on every line of code in this block? 

How are the blocks intended? Whitespaces? Tabs?

I think I will try to implement it, since it could be interesting for python aswell.

**Comment by EthanZeigler** [comment] 2021-02-26 17:30
Python is actually pretty easy to implement given it's based on indentation
and very strict about it. Ruby is harder, however ruby DOES have closing
tags. It's `end` or `}` depending on the start

Ethan Zeigler
ethanzeigler.com

Please excuse any typos. Sent from my phone.

**Comment by j0meinaster** [comment] 2021-02-27 20:36
It was not easy, but I guess I got it to work.

Please check the new released version 1.4.0.

Since I never wrote any ruby code, please **confirm** my idea:

To identify the start of a new block I expected to be the first word in line one of:
**['if', 'unless', 'elsif', 'else', 'case', 'while', 'until', 'for', 'def', 'class', 'begin', 'rescue']** or **'do'** somewhere in the line.

To identify the end of a block I expect one of the following words:
**['end', 'elsif', 'else', 'rescue']**

I defined that the opening needs to be the first word of the line, to skip "single line control statements" (which may have no 'end')
e.g. `return true if arr.empty? && n == 0`

If you find any bugs, please open a new issue and provide a ruby code snippet to reproduce.

I hope my extensions helps you :D

**Comment by EthanZeigler** [comment] 2021-02-27 21:08
This is great! Thank you so much for the effort. On Monday, I'll use it all
day and tell you if it's recognizing everything correctly.

Ethan Zeigler
ethanzeigler.com

Please excuse any typos. Sent from my phone.

**Comment by EthanZeigler** [comment] 2021-03-01 14:38
Bug 1: brackets/block start sequences in comments are parsed.
# begin
   ...
end -> peek says `# begin` is matching. This is probably a plugin-wide bug as it stands.

**Comment by j0meinaster** [comment] 2021-03-01 15:35
Since I am using only regex to find the matches, I will never be able to parse comments and strings (See known issues).

However start sequences are only allowed as first word in line, so this might really be fixable in this specific situation.

Can you please provide a simple code example where this match happens?

**Comment by j0meinaster** [comment] 2021-03-02 23:54
Could not reproduce with:

`# if @engine_state
if @engine_state  
    puts 'Engine is already Running'  
else  
    @engine_state = true  
    puts 'Engine Idle'  
end `

a "do" control structure in a comment will cause unwanted behavior for sure, but that's very hard to fix and not worth the effort (for now)

**Comment by EthanZeigler** [comment] 2021-03-03 00:15
Sadly I think the case I found was in fact a `do`. Don't worry about it. It's a super useful plugin i'll be using for a long time.

**Comment by EthanZeigler** [comment] 2021-03-05 15:50
Bug 2: `module` missing from the list of block starters

**Comment by j0meinaster** [comment] 2021-03-08 08:37
Thanks for the feedback. I was able to fix both:

1)  Comments starting with '#' are now ignored (especially for 'do', 'end' and inline control structures)
2) module added

Check version 1.4.2

Feel free to create any new ticket if you find another bug.

**Closed by j0meinaster** 2021-03-08 08:37 UTC
